version: '3.8'
services:
  movies:
    image: jagadeeshtadepalli/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: jagadeeshtadepalli/train:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
  dth:
    image: jagadeeshtadepalli/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: jagadeeshtadepalli/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
